# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: b88dd2797e87c70e58c90beae26f3da646d525319fedaeea3c2aa5d0fe382aa924e2224831b392b195680715fc3aba458b5d78a33cb83b5f58f82a9452d574ef

test:
  domain_name: example.com 
  secret_key_base: bc77d58b88c0c701cb87e01a9f7efc1a58d525fed7e93f4a36edae3b942dca48b1666790d819486bf099a987c6c907c5e1b4b565db7b064bca64da2f87b9b9ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
